#include "FormesGeometriques.h"
#include <math.h>



void FormesGeometriques::CalculerSurface(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D50 begin
{
   
    FormesGeometriques::Surface=  pow((x1 + x2),2) ;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D50 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void FormesGeometriques::CalculerPerimetre(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D54 begin
{
    FormesGeometriques::Perimetre = (x1 + x2)*2;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D54 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetSurface()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7D begin
{
    return FormesGeometriques::Surface;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetPerimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7F begin
{
    return FormesGeometriques::Perimetre;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D7F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
