#include "Utilisateur.h"
#include "TriangleRectangle.h"
#include "Rectangle.h"
#include "Cercle.h"
#include <iostream>


void Utilisateur::AfficherResultats()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D40 begin
{
    
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D40 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Utilisateur::ChoisirForme(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D42 begin
{
    m_CodeFormeChoisie = CodeForme;
    switch (m_CodeFormeChoisie)
    {

        case 0:
            TriangleRectangle triangle;
            break;
        case 1:
            Rectangle rectangle;
            break;
        case 2:
            Cercle cercle;
            break;

    }
    return 0;
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D42 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Utilisateur::SaisirLesParametres()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D44 begin
{
    float m_x1;
    float m_x2;
    switch (m_CodeFormeChoisie)
    {

    case 0:
        //m_x1 = base en centimetre 
        std::cout << "gimme base: " << std::endl;
        std::cin >> m_x1;
        //m_x2 = hauteur en centimetre 
        std::cout << "gimme hauteur: " << std::endl;
        std::cin >> m_x2;
        break;

    case 1:
        Rectangle rectangle;
        //m_x1 = largeur en centimetre 
        std::cout << "gimme largeur: " << std::endl;
        std::cin >> m_x1;
        //m_x2 = hauteur en centimetre 
        std::cout << "gimme hauteur: " << std::endl;
        std::cin >> m_x2;
        break;
    case 2:
        Cercle cercle;
        //m_x1 = diametre en centimetre 
        std::cout << "gimme diameter: " << std::endl;
        std::cin >> m_x1;
        m_x2 =0 ;
        break;

    }

    
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D44 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Utilisateur::ExecuterLesCalculs()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D47 begin
{
    
    
}
// section -64--88-1-58--553bbdf8:13b14881301:-8000:0000000000000D47 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
