#include "CERCLE.h"




double CERCLE::CalculerSurface(double diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D6C begin
{
    return 0.0;
}
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D6C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double CERCLE::CalculerPerimetre(double diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D6F begin
{
    return 0.0;
}
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D6F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
