#include "Cercle.h"




double Cercle::CalculerSurface(double Diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D68 begin
{
    return 0.0;
}
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D68 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Cercle::CalculerPerimetre(double Diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D6B begin
{
    return 0.0;
}
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D6B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
