#include "Ex1.h"




void Ex1::SaisirParameters(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D2B begin
{
}
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D2B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Ex1::main()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D2E begin
{
    return 0;
}
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D2E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::ExectuterLesCalculs(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D30 begin
{
    
}
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D30 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::AfficherResultats(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D33 begin
{
    
}
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D33 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Ex1::ChoisirForme()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D36 begin
{
    return 0;
}
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D36 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
