#include "FormesGeometrique.h"




double FormesGeometrique::CalculerSurface(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D42 begin
{
    return 0.0;
}
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D42 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometrique::CalculerPerimetre(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D46 begin
{
    return 0.0;
}
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D46 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometrique::GetSurface()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D4A begin
{
    return 0.0;
}
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D4A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometrique::GetPerimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D4C begin
{
    return 0.0;
}
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D4C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
