#include "FORMESGEOMETRIQUES.h"




double FORMESGEOMETRIQUES::CalculerSurface(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D4E begin
{
    return 0.0;
}
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D4E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FORMESGEOMETRIQUES::CalculerPerimetre(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D52 begin
{
    return 0.0;
}
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D52 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FORMESGEOMETRIQUES::GetSurface()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D56 begin
{
    return 0.0;
}
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D56 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FORMESGEOMETRIQUES::GetPerimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D58 begin
{
    return 0.0;
}
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D58 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
