#include "Rectangle.h"




double Rectangle::CalculerSurface(double Largeur, double Hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D5D begin
{
    return 0.0;
}
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D5D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Rectangle::CalculerPerimetre(double Largeur, double Hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D60 begin
{
    return 0.0;
}
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D60 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
