#include "TriangleRectangle.h"




double TriangleRectangle::CalculerSurface(double Base, double Hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D53 begin
{
    return 0.0;
}
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D53 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double TriangleRectangle::CalculerPerimetre(double Base, double Hauter)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D57 begin
{
    return 0.0;
}
// section -64--88-103-95-5262175:1931a7fae34:-8000:0000000000000D57 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
