#include "Conducteur.h"




int Conducteur::Conduire()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-57--cb165d3:193862fefe3:-8000:0000000000000A51 begin
{
    return 0;
}
// section 10--28--98-57--cb165d3:193862fefe3:-8000:0000000000000A51 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Conducteur::Marcher()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-57--cb165d3:193862fefe3:-8000:0000000000000A56 begin
{
    return 0;
}
// section 10--28--98-57--cb165d3:193862fefe3:-8000:0000000000000A56 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
