#include "moteurEnLigne .h"




double moteurEnLigne ::Tourner(double essence )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-57--cb165d3:193862fefe3:-8000:0000000000000A27 begin
{
    return 0.0;
}
// section 10--28--98-57--cb165d3:193862fefe3:-8000:0000000000000A27 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int moteurEnLigne ::Tourner(char essence)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-57--cb165d3:193862fefe3:-8000:0000000000000A37 begin
{
    return 0;
}
// section 10--28--98-57--cb165d3:193862fefe3:-8000:0000000000000A37 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
