#include "moteur.h"




int moteur::Tourner()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-57--cb165d3:193862fefe3:-8000:0000000000000A1E begin
{
    return 0;
}
// section 10--28--98-57--cb165d3:193862fefe3:-8000:0000000000000A1E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void moteur::Lubrifier(float huile_l)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-57--cb165d3:193862fefe3:-8000:0000000000000A2B begin
{
    
}
// section 10--28--98-57--cb165d3:193862fefe3:-8000:0000000000000A2B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
