#include "moteurEnEtoile.h"




double moteurEnEtoile::Tourner()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-57--cb165d3:193862fefe3:-8000:0000000000000A29 begin
{
    return 0.0;
}
// section 10--28--98-57--cb165d3:193862fefe3:-8000:0000000000000A29 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void moteurEnEtoile::Tourner(double piston)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-57--cb165d3:193862fefe3:-8000:0000000000000A39 begin
{
    
}
// section 10--28--98-57--cb165d3:193862fefe3:-8000:0000000000000A39 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
