#include "Ex1.h"







double Ex1::TRIANGLERECTANGLE::CalculerSurface(double base,, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D5E begin
{
    return 0.0;
}
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D5E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Ex1::TRIANGLERECTANGLE::CalculerPerimetre(long double largeur,)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D67 begin
{
    return 0.0;
}
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D67 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element



int Ex1::Main()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D3A begin
{
    return 0;
}
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D3A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Ex1::ChoisirForme()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D3C begin
{
    return 0;
}
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D3C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::SaisirParametres(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D3E begin
{
}
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D3E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::ExecuterLesCalculs(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D40 begin
{
}
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D40 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::AfficherResultats(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D42 begin
{
}
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D42 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
