#include "RECTANGLE.h"




double RECTANGLE::CalculerSurface(double largeur, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D73 begin
{
    return 0.0;
}
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D73 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double RECTANGLE::CalculerPerimetre(double largeur, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D77 begin
{
    return 0.0;
}
// section 10--28--98-99--373ca81a:1931a7a8a3d:-8000:0000000000000D77 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
