#include "Dessinateur.h"




void Dessinateur::ConstruireFigure(signed char Choix)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-33-77d6db45:13c586c4ff5:-8000:0000000000000CAD begin
{
}
// section -64--88-1-33-77d6db45:13c586c4ff5:-8000:0000000000000CAD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Dessinateur::SaisirPositionXY(int NoPoint)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-33--f43e65:13c5870e6ba:-8000:0000000000000B0C begin
{
    
}
// section -64--88-1-33--f43e65:13c5870e6ba:-8000:0000000000000B0C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Dessinateur::DessinerFigure()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-33--f43e65:13c5870e6ba:-8000:0000000000000B0F begin
{
    
}
// section -64--88-1-33--f43e65:13c5870e6ba:-8000:0000000000000B0F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
