#include "Figure.h"




void Figure::EffectuerSaisie(int NoPoint)
{
    
}


void Figure::Dessiner()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D89 begin
{
    
}
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D89 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Figure::Figure()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D8B begin
{
    PairePoints[] = {0};
    std::cout << "Constructeur figure" << std::endl;

}
// section -64--88-1-58-75afad:13c59679ed7:-8000:0000000000000D8B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Figure::~Figure()
{
    std::cout << "Destructeur figure" << std::endl;
}

